#!/bin/sh

touchpadId=10
touchpadProps=`xinput list-props $touchpadId`
pattern="Device Enabled \\(142\\): *1"
if [[ $touchpadProps == *"Elan Touchpad"* ]]
    then
    echo $touchpadProps | egrep -qo "$pattern"
    case $1 in
        "toggle"*)
            if [[ $? -eq 0 ]]
            then
                xinput disable $touchpadId
            else
                xinput enable $touchpadId
            fi
            ;;
        "query"*)
            if [[ $? -eq 0 ]]
            then
                echo ""
                echo ""
                echo "#FF0000"
            fi
            ;;
    esac
fi
